-- Unfortunately these steps cannot be performed by the automatic hbm2ddl schema generation
-- Also, we cannot use the foreign key constraint from event to geometry, since MySQL doesn't 
-- support foreign key constraints from innodb to myisam tables.

--remove autogenerated foreign key
alter table Event drop foreign key FK_EVENT_GEOM;
ALTER TABLE TsGeometry ENGINE = MyISAM;
CREATE SPATIAL INDEX sp_geom ON TsGeometry (geometryCollection);

--remove autogenerated foreign key
alter table Event drop foreign key FK_EVENT_EVENTSEARCHTEXT; 
ALTER TABLE EventSearchText ENGINE = MyISAM;
CREATE FULLTEXT INDEX ft_event ON EventSearchText (summary, _where, usertags, description, source);

-- This is a laboratory class, not to be used in production
-- ALTER TABLE address ENGINE = MyISAM;
-- CREATE SPATIAL INDEX sp_addr ON address (addressLocation);
