-- Unfortunately these steps cannot be performed by the automatic hbm2ddl schema generation
-- Also, we cannot use the foreign key constraint from event to geometry, since MySQL doesn't 
-- support foreign key constraints from innodb to myisam tables.

--remove autogenerated foreign key
alter table Event drop foreign key FK_EVENT_GEOM;
ALTER TABLE TsGeometry ENGINE = MyISAM;
CREATE SPATIAL INDEX sp_geom ON TsGeometry (geometryCollection);

--remove autogenerated foreign key
alter table Event drop foreign key FK_EVENT_EVENTSEARCHTEXT; 
ALTER TABLE EventSearchText ENGINE = MyISAM;
CREATE FULLTEXT INDEX ft_event ON EventSearchText (summary, _where, usertags, description, source);

-- user roles
INSERT INTO Role (id,created,lastModified,version,name) VALUES 
(1,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,0,'admin'),
(2,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,0,'edit'),
(3,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,0,'canDelete'),
(4,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,0,'canBlock'),
(5,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,0,'canMove');

-- Admin user pw='cat'
INSERT INTO User (id,created,lastModified,version,email,username,password) 
VALUES(1,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0,'frank@fsanmiguel.com','frank','/aPky1NqzLtdu/+W+x/Mr9gQTiUO0SeT');

--give him all the admin roles
INSERT INTO User_Role (user_id, roles_id) VALUES
(1,1),(1,2),(1,3),(1,4),(1,5);

--positional accuracies
ALTER TABLE PositionalAccuracy AUTO_INCREMENT=0; 
INSERT INTO PositionalAccuracy (id, name, visible) VALUES
(1, 'UNSPECIFIED', true),
(2, 'REGION', true),
(3, 'CITY', true),
(4, 'NEIGHBORHOOD', true),
(5, 'ADDRESS', true),
(6, 'PINPOINT', true);
