-- Unfortunately these steps cannot be performed by the automatic hbm2ddl schema generation
-- Also, we cannot use the foreign key constraint from event to geometry, since MySQL doesn't 
-- support foreign key constraints from innodb to myisam tables.

--remove autogenerated foreign key
alter table Event drop foreign key FK_EVENT_GEOM;
ALTER TABLE TsGeometry ENGINE = MyISAM;
CREATE SPATIAL INDEX sp_geom ON TsGeometry (geometryCollection);

--remove autogenerated foreign key
alter table Event drop foreign key FK_EVENT_EVENTSEARCHTEXT; 
ALTER TABLE EventSearchText ENGINE = MyISAM;
CREATE FULLTEXT INDEX ft_event ON EventSearchText (summary, _where, usertags, description, source);

-- user roles
INSERT INTO role (id,created,lastModified,version,name) VALUES 
(1,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,0,'admin'),
(2,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,0,'edit'),
(3,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,0,'canDelete'),
(4,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,0,'canBlock'),
(5,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,0,'canMove');

-- Admin user pw='cat'
INSERT INTO user (id,created,lastModified,version,email,username,password) 
VALUES(1,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0,'frank@fsanmiguel.com','sanmi','P5iePyfcng7DOJ/IVfFCw9QPDFA=');

--give him all the admin roles
INSERT INTO user_role (user_id, roles_id) VALUES
(1,1),(1,2),(1,3),(1,4),(1,5);

